apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev-mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: <base64-encoded>
  MYSQL_USER: <base64-encoded>
  MYSQL_PASSWORD: <base64-encoded>
  MYSQL_DATABASE: <base64-encoded>